### ISSUE TITLE
Overlapping Work

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/VisualizationG5#14]
Hey,

just as a suggestion: it does not make sense that both teams do a fully fleched Web App with all components. It would be better if one of the team focuses on the big picture, like the main framework and detailed views while the other team comes up with a great idea how to navigate the "social network graph". 

So: maybe you can coordinate a bit with your colleges so we don't end up with two systems that will run in parallel. Ideally we can maybe integrate one into the other.

@MusicConnectionMachine/group-6 
https://github.com/MusicConnectionMachine/VisualizationG6/issues/11

**Comment by chaoran-chen** [comment]
Closed since it will be discussed in MusicConnectionMachine/VisualizationG6#11
