### ISSUE TITLE
Person-Person Graph

### ISSUE THREAD

**Issue by chaoran-chen** [MusicConnectionMachine/VisualizationG5#16]
After the tasks for setting up are mostly defined and done, I think that it's time to start with the core issues of this project.

I would like to suggest an interactive graph that shows the (up to 7?) most important people related to a person, and it should be possible to select if all kind of people should be presented or only, e.g., composers.

![img_8803](https://cloud.githubusercontent.com/assets/18666552/23546031/2469892a-fffe-11e6-9af7-839c94721536.JPG)

What do you think?

**Comment by martomi** [comment]
I like the idea. I'll start looking into D3.js and Cytoscape.js to see what would be more suitable for that kind of visualization.

**Comment by kordianbruck** [comment]
http://visjs.org/network_examples.html
http://sigmajs.org/
http://jsnetworkx.org/

Just to name a few - pick the best :P

**Comment by sacdallago** [comment]
Cytoscape might be an overkill! But if the network is really big, it might be the only solution.

Key here is to understand _how big_ (number of nodes and number of edges) the network is going to be. Also: it would be cool if the graph would render in a hyperlink fashion: clicking on one item loads new data into the graph and deletes some old nodes (for example). <-- not very trivial, AFAIK

**Comment by martomi** [comment]
@sacdallago Your suggestion sounds very similar to that http://www.wineandcheesemap.com (try clicking on some nodes). It's based on Cytoscape. Do you have experience with any more lightweight library that you could recommend instead of Cytoscape. D3 seems to be very flexible and any implementation would be possible, but on the other hand it probably requires more work as it is not specifically designed for graph networks.

**Comment by martomi** [comment]
So here's the result of a few experiments I did with different libraries:

[VisJS Demo](http://jsfiddle.net/dq3fc0nz/3/): I like the simplicity, but it's also somewhat limiting. E.g I don't see an obvious way to move the labels inside the nodes. The library doesn't not provide a configuration possibility for that. 

[Cytoscape Demo](http://jsfiddle.net/kbgurfs7/): A bit more advanced, lots of options to configure everything imaginable. Requires more documentation reading to figure out how it works. But also seems to offer more or less everything we might need.

And of course D3 is always a viable option. Here's an interesting [JSFiddle](https://jsfiddle.net/JVAdams/bTHk2/2/) I found implemented with D3. It's noticeably more code to setup the graph, but offers the highest flexibility of all approaches.

Unless we're happy with the look offered by VisJS, I suggest that we choose either Cytoscape or D3.

**Comment by chaoran-chen** [comment]
> Key here is to understand how big (number of nodes and number of edges) the network is going to be.

I believe that the visible part of the network shouldn't be that large because it should only show the most important relationships. Furthermore, I think that the nodes should contain, if available, a picture of a person, so that it would not be possible to display too many nodes.

> it would be cool if the graph would render in a hyperlink fashion: clicking on one item loads new data into the graph and deletes some old nodes

I like it!

**Comment by sacdallago** [comment]
I have seen people using D3 for graphs and it's _not bad_. This being said, D3 is really bare-bone and you can configure every aspect of it from bottom up. Cytoscape is more integrated and some behaviours are just a matter of _enabling_ plugins. Also: D3 is not good at handling huge **dynamic** graphs (where the dynamic par is: where do you place the node in space? Fixed positions vs calculated positions? A friend of mine has overcome the limitation by calculating the spacial positions in backend and then visualising fixed positions in the frontend).

For example: I can imagine that there is an out of the box solution for cytoscape.js to do the hyperlink story as written above and in the wine example, but: is it nice? Is it performant?

With D3 I can imagine how you really have to code the logic of adding a node and removing other nodes when clicking on a specific node, which you can **animate better**, you have more control over what's going on and which data is being stored, etc.

**Comment by vviro** [comment]
@chaoran-chen I believe that providing a higher information density option (possibly with an interactive filtering functionality?) would also be important. Given the size of the analyzed dataset there will be interesting findings that are not well known or most important, but which we certainly want to make available and discoverable. How to do that is an interesting question.

**Comment by martomi** [comment]
We're currently leaning more toward a solution with a small number of nodes on the screen at any given time. This would allow us to provide better browsing experience to the user. 

Graphs with a lot of nodes can be overwhelming and hard to analyze unless we're looking for very specific trends which can be observed only by looking at the big picture. I believe it's better to do a separate implementation for a graph of that type in case we need it.

However, in order to reduce the number of nodes we need to think of clever ways to group them. I've opened a separate issue to discuss that: #24 .

<img width="573" alt="screenshot 2017-03-10 23 36 00" src="https://cloud.githubusercontent.com/assets/3739458/23816154/92cb3d9e-05eb-11e7-8db7-4ac706840e1a.png">

**Comment by gyachdav** [comment]
I really like this idea. It makes sense for a data exploration tool to dynamically show information on-demand and not dump all data onto the screen at once. The "wine and cheese" example does something similar but not exactly what you want. As I see it, expanding a group keeps the original composer in the middle but adds more nodes to the network. The main considerations here should be:

1. Make it intuitive for end users to click on modes that represent groups. 
2. Have the ability to collapse back expanded nodes. 
3. Make the network presentation smoothly and elegentaly scale as more nodes are added.  
4. Find a way to limit the size of presented network.

**Comment by goldbergtatyana** [comment]
Are you considering having an overview of relationships also in a text format, like a table listing all connections in the graph?

**Comment by martomi** [comment]
Maybe, a table listing shouldn't be very hard to add. Then again we should have some sort of filtering to avoid rendering huge tables with endless scroll 😄

**Comment by goldbergtatyana** [comment]
Yep, true! One of the filters could be a srolling bar that would limit table entries only to a certain weight. Default could be for example a weight of 0.9. A user could then scroll a bar and let also entries with a lower weight appear. Maybe we could also allow user to download a table with _all_ entries as an excel sheet.

**Comment by gyachdav** [comment]
I think that an export feature into CSV, TSV, JSON makes sense. I would avoid having a table as a visual object though. The graph/network is the most intuitive visual we have to represent relationships.  let's stick to it.

**Comment by goldbergtatyana** [comment]
A graph is a very strong visual, I agree! In the discussion above I read that only 7 (?) strongest relationships are planned to be shown in the graph. This number appears low to me, however showing more than that can be a mess (and so less of a use). So, I was thinking of having a different view (like switching tabs) where a user can go to a text visualization of the results and see also weaker connections (e.g. married to another musician, dueled with yet a third musician). I can imagine that the strong connections will represent strong, already well known information. Weak connections however will be those that might be of a higher interest, as they probably dont represent main (internet) knowledge.

**Comment by chaoran-chen** [comment]
Only 7 relationships was an earlier idea but we decided to show much more by grouping them as described in #24

**Comment by martomi** [comment]
I'm going to close this issue since a first iteration of the graph has already been implemented and the issue itself is becoming quite big and not actionable. Will open separate issues for smaller tasks on the person graph instead.
