### ISSUE TITLE
Create mock data

### ISSUE THREAD

**Issue by chaoran-chen** [MusicConnectionMachine/VisualizationG5#2]
Write some mock data for the entities:
* Composers
* Music works
* Musicians and groups of musicians (people, orchestras, choirs, ensembles, etc)

and some data about their relations. See: https://musicbrainz.org/doc/Style/Relationships

**Comment by sacdallago** [comment]
@MusicConnectionMachine/group-1 @MusicConnectionMachine/group-2 just pinging
