### ISSUE TITLE
Visuzalition of Work Data

### ISSUE THREAD

**Issue by lustoykov** [MusicConnectionMachine/VisualizationG5#25]
Proposal: 

Implement a React Component to visualize work data.

Use it in: 

- Search for work data - display list of such components
- Browse work data - display list of such components
- Links and integration with #17 - link to author's timeline from work data
- Links and integration with #17 - @chaoran-chen could reference the work data component or implement basic data info and when you "click more" we show more info with this component.

What's your opinion? Do you have better suggestions for features or should I do this one?

**Comment by chaoran-chen** [comment]
Hi @lustoykov, thanks for the proposal! I'm not sure if I understand your idea. Could you explain it more detailed?
* Which kind of visualization do you have in mind? 
* Should this component be able to display general information of all entities? Does it replace #5?
* I guess that "Search for work data" is the search function we already have implemented?
* What do you mean with "Browse work data"? Is it a component that we have to implement, or is it just the general navigation through our site including the search?

**Comment by lustoykov** [comment]
True this is not really need, I'll reopen if the idea matures more in my mind.
