### ISSUE TITLE
Map View

### ISSUE THREAD

**Issue by chaoran-chen** [MusicConnectionMachine/VisualizationG5#26]
As we can see in this [table](https://musicbrainz.org/relationships) (especially [here](https://musicbrainz.org/relationships/area-recording) and [here](https://musicbrainz.org/relationships/place-work)), there are a lot of data and relationships containing geographical information. Thus, I would like to propose a map view. I'm thinking of a visualization similar to [Drivenow](https://de.drive-now.com/#!/carsharing/muenchen) but with important events instead of cars, and where it zoomed out at the beginning (maybe showing the full world).

What do you think?

**Comment by martomi** [comment]
Agree, I had a similar idea looking at [D3's Geographic Projections](https://github.com/d3/d3-geo) earlier this week. Not sure if D3's representation would be better than Google Maps as in your example with DriveNow.

Edit: Check out this JSFiddle [demo](http://jsfiddle.net/xavipolo/v3d39ggg/).

**Comment by lustoykov** [comment]
http://leafletjs.com/ is also a possible solution

**Comment by martomi** [comment]
In my opinion D3's representation gives us a nice more abstract representation, the other map solutions seem more meaningful to me if you actually intent to navigate to the specified location, which doesn't seem to be the case for us.

**Comment by lustoykov** [comment]
I like the d3 proposal more as well

**Comment by sacdallago** [comment]
Mh. If you want something navigable, use leaflet. If you want an infographic-style visualisation, use D3.

## I'd go for leaflet!

This being said, **put this in the backlog, but work on getting the main requirements done first**  https://en.wikipedia.org/wiki/Lean_software_development

**Comment by martomi** [comment]
@MusicConnectionMachine/group-6 That's the map view we were talking about today. If we divide the work between the two groups so that we don't do overlapping features, this would be a good place to start.

**Comment by chaoran-chen** [comment]
I'll close this issue here since it will be done by @MusicConnectionMachine/group-6.
