### ISSUE TITLE
Libraries for the Components

### ISSUE THREAD

**Issue by chaoran-chen** [MusicConnectionMachine/VisualizationG5#33]
Hey. I think that we should speak a bit about the libraries we want to use for our components. Currently, D3 is used for the Person-Graph and vis.js for the timeline. 

* Do we also want to use some general libraries such as jQuery?
* How do we want to fetch the JSON-data? Using d3 (even if the component does not use d3)? Using XMLHttpRequest, or `fetch` with polyfill? jQuery?
* Is there a need for a .CSS library? We are using Bootstrap for our express site, but we cannot assume that it is included in every host site that uses the component. Thus, we need to take care of things like the default font in our components.
* What do you think about an icon library ([Font Awesome](http://fontawesome.io/), [Typicons](http://www.typicons.com/))?

**Comment by lustoykov** [comment]
here my 2 cents

- React makes jQuery unneeded
- fetch is simplest and most versatile
- I added react-bootstrap-4 to our components, will come with pull request
- Feel free to add any icon set you wish, I don't mind : - )

**Comment by kordianbruck** [comment]
Please just decide if a full icon set is really required. If you do use one, just use one of them - not multiple. 

Icon fonts add a lot of traffic... (Especially if they are included on a separate site)

**Comment by chaoran-chen** [comment]
Yes, that's a good point. Therefore the question to all: do you have any need for an icon set? I needed one icon for external links and will certainly need some few more, but if none of you need it, I can do it otherwise.

(@martomi? @Binabiko?)

**Comment by martomi** [comment]
No icons required from my side at this point. I agree with @lustoykov on the other points 👍

**Comment by chaoran-chen** [comment]
Good, then no more (general) libraries for the moment. -closed-
