### ISSUE TITLE
Building the final bundle + API to host site

### ISSUE THREAD

**Issue by chaoran-chen** [MusicConnectionMachine/VisualizationG5#35]
Now that we have the first prototypes of some widgets, we should start to discuss how we want to ship them and how the host sites can interact with them. I think that our build (and all of our components) should support the following three points.

1. Provide a single JavaScript (and maybe CSS) file, e.g.
```
music.min.js
music.min.css
```
2. The host site developer can create widgets in such a way:
```
<div id='person-graph'></div>
...
const personGraph = new music.PersonGraph('#person-graph', {
    personId: ...,
    ...
});
```
3. Fire events:
```
personGraph.on('personClicked', personClickedHandler);
```

I believe that this issue has a quite high priority since it is a must-to-have, and should be implemented soon.

**Comment by chaoran-chen** [comment]
@vviro That's the topic which we have talked about the last time, right?

**Comment by kordianbruck** [comment]
I think an iframe will be simpler to do at first, but has less flexible configurability. 

In any case, if you include a JS script you can dynamically add the stylesheet on load.

**Comment by chaoran-chen** [comment]
An iframe would be simpler for sure, but then, I don't know how the components should notify the host site about events appropriately, which seems to be an important requirement according to @vviro .

I think that a good and sustainable setup is worth the effort, and I can attack this issue with pleasure after the presentations.

**Comment by kordianbruck** [comment]
Alright, yes, I was not aware of that requirement. Excuse my comment then and proceed. Nothing to see here :construction:

**Comment by martomi** [comment]
We had another discussion with @vviro and it turns out it is actually possible to notify the host site about events from within the iframe by defining callbacks. Also from his experience it works quite well for widgets and we decided to take that same approach. Thus closing this issue.
