### ISSUE TITLE
Merge Pagination with Search of G6

### ISSUE THREAD

**Issue by lustoykov** [MusicConnectionMachine/VisualizationG5#40]
- G6 has nice design on their search component, but do not have Pagination, integrate G6's nice design into our Pagination. Also @chaoran-chen  has build Search component with better designed suggestion than our current pagination, so combine those suggestion into pagination as well.

- [ ] Integrate G6 Search's design into Pagination
- [ ] Integrate nice Suggestion's design implemented by @chaoran-chen into Pagination

**Comment by chaoran-chen** [comment]
G6 does already have a Pagination (which is quite nice designed). Try it by searching for Beethoven. But they haven't an autosuggestion.
http://visualization-g6.surge.sh/

**Comment by martomi** [comment]
@chaoran-chen  By pagination we mean actually showing the pages under the results so you can directly go to page 10 without having to click 10 times on the next button. I'm not sure we have the use case and need to support this kind of pagination, but Google has it and so far we've oriented ourselves to their implementation of search.

Personally, I like the simplicity of the < back | next > buttons.

**Comment by lustoykov** [comment]
Closing this issue, since G6 is responsible for that.
