### ISSUE TITLE
Merge work of G5 + G6

### ISSUE THREAD

**Issue by lustoykov** [MusicConnectionMachine/VisualizationG5#41]
OK, I think we've come to a point where it makes sense to combine forces in order to create a great product. We'd like to invite G6 to join our project.

G6 has really nice landing page, we don't have one, it would be really nice if they can integrate their landing page into our project.

- [ ] G6 integrate landing Page into G5's project

Also, we have one component which overlaps - we have pagination + search, they have search + very good design. I'd like to take over here and merge both. See Issue #40.

- [ ] Merge Pagination from G5 and Search Design from G6 #40 

I'd also like to help @martomi with the Person-to-Person Graph, @chaoran-chen is also busy with the timeline, so G5 lacks resources currently to finish #26. We'd like to invite G6 to finish this feature.

- [ ] @martomi and @lustoykov implement fully Person-to-Person Graph
- [ ] @chaoran-chen finalize timeline
- [ ] G6 finish #26 

@Binabiko will implement a Feedback Component as far as I remember - @Binabiko can you elaborate on that, what is this component?

- [ ] @Binabiko implement Feedback Component (and explain what its purpose?)

What do you guys think?

**Comment by chaoran-chen** [comment]
Here are two corresponding issues to the Feedback / Commenting Component:
https://github.com/MusicConnectionMachine/api/issues/25
https://github.com/MusicConnectionMachine/VisualizationG6/issues/23

**Comment by joern-vh** [comment]
Yep. So mainly as mentioned above it should be a commenting Component - think it's Awesome to Share ones opinion on Music with other People.

**Comment by demirdagemir** [comment]
Sounds cool, but like we talked today, how are we gonna do this? A separate repo, where everybody will work from now on, or are we going to work in parallel from our repos and combine them in one of our projects? Or, by "joining" you mean we move to your repo?

**Comment by ysdevys** [comment]
I think separating the work and work parallel but on different features in our repos would be better, so we can continue in our smaller teams and don't loose time in merging right now.
I like the idea of the map and leafletJS. We can do this instead of the graph so we don't overlap.

**Comment by kordianbruck** [comment]
I think separate development is good for now - but please, for the love of god, think of how we can merge the individual components into one project some day in the next two weeks.

**Comment by joern-vh** [comment]
![photo-2017-03-23-12-33-14_2628](https://cloud.githubusercontent.com/assets/25976634/24246069/e55dfcac-0fc5-11e7-9135-ef814e7bcc5f.JPG)

Group Assignments

**Comment by kordianbruck** [comment]
@Binabiko so we are not merging the groups right? Can you create dedicated issues for the assigned tasks please?

**Comment by joern-vh** [comment]
Yes I'll do so later!

**Comment by syncall** [comment]
Actually I would suggest to merge the projects not too late. It will be harder the later we get with the projects

**Comment by ysdevys** [comment]
If we merge ill set up Integration mainline to be build and tested with travis

**Comment by joern-vh** [comment]
@kordianbruck I just created new Issues and assigned them.

**Comment by lustoykov** [comment]
Closing this issues, as tasks are assigned to groups
