### ISSUE TITLE
Relationship exploration widget

### ISSUE THREAD

**Issue by martomi** [MusicConnectionMachine/VisualizationG5#42]
As per latest discussion with @vviro and @gyachdav we want to build a widget for exploring the relationships of an entity through a **simple text table** (instead of bubble charts).

Initially the table should only show the few most relevant relations to an entity. We need a **search bar** on top that would allow user to search for **both** relations and entities. 

Naturally, only entities and relations that are connected to the currently viewed entity would appear in the search results.

[IMDB's Cast & Crew table](http://www.imdb.com/title/tt2488496/fullcredits?ref_=tt_cl_sm#cast) can be used as initial point of reference. It's expected that we'll have more information to show about a specific relation, so we might want to show that information on hover or click.

We could probably reuse our already built search component for this widget.

Also the widget is intended for integration in pages such as http://imslp.org/wiki/Abschiedsgesang,_WoO_102_(Beethoven,_Ludwig_van) So we should make the styling somewhat compatible or give configuration options for the colors.

**Comment by lustoykov** [comment]
See 
https://github.com/MusicConnectionMachine/RelationshipsG3/issues/27

**Comment by lustoykov** [comment]
Close in favour of #56
