### ISSUE TITLE
Make widgets available through iframe

### ISSUE THREAD

**Issue by martomi** [MusicConnectionMachine/VisualizationG5#43]
We need to provide a way to register callback functions from the parent page in order to execute actions from inside the iframe without triggering the cross-domain scripting error.

**Comment by kordianbruck** [comment]
I thought this was impossible but this thread on SO says otherwise: https://stackoverflow.com/questions/4181433/creating-a-javascript-callback-in-an-iframe

**Comment by joern-vh** [comment]
We get now the Information of what Musician or what Music Piece we have a look at. I pass this to the iFrame by adding it to the URL.
We just need to get the Information about which Musician/Music Piece we are looking at - right?

**Comment by martomi** [comment]
Solved in #54
