### ISSUE TITLE
Create basic pages for the 3 entities

### ISSUE THREAD

**Issue by chaoran-chen** [MusicConnectionMachine/VisualizationG5#5]
Pages for
* Composers
* Music works
* Musicians and groups of musicians (people, orchestras, choirs, ensembles, etc)

with some basic information.

**Comment by lustoykov** [comment]
I'm starting to work on that today.

**Comment by lustoykov** [comment]
- [x] Implement a Pagination component (Footer, Header and Filter)
- Footer displays numbers 1... 8, 9, 10, ... 30 (current page is 9, last page is 30)
- Header just for visual purpose
- Filter - the user can type anything and it triggers a callback with the value

The Pagination should accept following properties:
- total - total number of entities
- limit - number of entities per page
- currentPage - current page
- entities - data to display
- filterEntities - data to display when uses filter
- EntityComponent - the component which displays the entity
- handlePageClick(number) - function is triggered when page number is clicked
- handleFilterChange(string) - function is triggered when user types in filter

- [x] Style Pagination
- [x] Implement Composer component to display a composer
- [x] Implement Composers component which integrates Pagination with Composer
- [ ] Same for musicians
- [ ] Same for works

**Comment by chaoran-chen** [comment]
Closed since we will not build an own site anymore.

**Comment by kordianbruck** [comment]
@chaoran-chen did you agree that you will supply the already done work to the other group so they can reuse it?

**Comment by chaoran-chen** [comment]
Yes, we did. We decided together that group 6 will build a React-SPA and that they can import and use our React components.
