### ISSUE TITLE
Fill backlog

### ISSUE THREAD

**Issue by chaoran-chen** [MusicConnectionMachine/VisualizationG5#52]
Our backlog is empty. [Die Welt ist fertig?](https://www.youtube.com/watch?v=Npozv5tJ9ek)

If not, what are our next steps? @Binabiko told me that #43 will be done by today evening or at the latest by tomorrow so that #42 will be our only open issue. Should we all work on it in the next 12 days? Should we further improve the timeline? (how? ideas?) Or should we build another component?

(Also @MusicConnectionMachine/jstech, @MusicConnectionMachine/group-6)

**Comment by martomi** [comment]
If there are no other component requirements, maybe we should all just help with the API as there seems to be quite a bit of work remaining there.

**Comment by gyachdav** [comment]
You hit all your milestones? Can we see a demo of all you worked on? Can your widgets be integrated into IMSLP? Can they be integrated into our own SPA? Are you involved in creating the SPA?

**Comment by joern-vh** [comment]
I'm currently providing the iFrame functionality for our Components. I've tested integrating a Widget into Imslp and pass Information about what this Site is about to the IFrame content (by injecting) - works so far. I guess that I'll finish the Widget Setup by tomorrow (including a documentation like @vviro did for his project).

**Comment by martomi** [comment]
@Binabiko Now that you mention it, I remember @vviro suggested that we do integration of the iframe in the IMSLP website and provide this demo integration so it can be shown exactly how it would look like in their website. Make sure to commit those files in addition to the documentation view as well 👍

**Comment by chaoran-chen** [comment]
@gyachdav Here are our current components:
* [Timeline](http://54.68.164.199:8080/timeline-app.html)
* [Relation App (still under development)](http://54.68.164.199:8081/relations-app.html)
* [Small experiment to display relations with bubbles](http://54.68.164.199:8082/)

I assume that our widgets can be integrated into the SPA but we are not really involved. (@MusicConnectionMachine/group-6, can you need any help with the SPA or your components?)

**Comment by goldbergtatyana** [comment]
Hi Guys, very happy to see demos for three widgets. Thumbs up! 
I very much like the [Timeline ](http://54.68.164.199:8080/timeline-app.html#) widget. I see that there are several placeholders and the information is rather sparse. I am wondering how the information will be displayed for some real data? Could you provide an example for real Mozart data? Also, will the widget be available for music pieces and musicians as well?

**Comment by goldbergtatyana** [comment]
[The second widget ](http://54.68.164.199:8081/relations-app.html) is under development, so I hold off from giving feedback to it at the moment.

[The third widget ](http://54.68.164.199:8082/), though not tagged as such, it seems to me to be under development as well. The idea of how to display the info is really cool, its impressive to see how creative this solution and implementation are! Here I am wondering about the following items:
- why is the display window small and cannot be expanded as in widget 1?
- how are titles for the circles created? Having the name Mozart appearing in 1/3 of them is not informative
- what do the colors mean? It would be great having a legend explaining the colors
- same goes for the size of the circles. Is there any meaning behind?
- how about grouping the circles by colors?

**Comment by chaoran-chen** [comment]
Hi @goldbergtatyana! Thank you very much for the feedback!

[Timeline](http://54.68.164.199:8080/timeline-app.html): I have just inserted the data for Bach from [here](https://github.com/MusicConnectionMachine/api/issues/22#issuecomment-289942908) which contains 15 items. Currently, we have only discussed it for artists (but @ansjin, what do you think? Could you also provide data for music pieces?)

I have also tried to insert some randomly generated data (in total 115 items) to see how it will look like. Here are two screenshots:

Preview-mode (without zoom):
![timeline1](https://cloud.githubusercontent.com/assets/18666552/24635645/e8edf92c-18d4-11e7-9dc4-c348835546a9.png)
Full-screen-mode (zoomed-in):
![timeline2](https://cloud.githubusercontent.com/assets/18666552/24635646/e8ef626c-18d4-11e7-9a69-ebdc652bdcc3.png)

[The third widget](http://54.68.164.199:8082/): I called it only an "experiment" because it is based on an early idea to visualize relationships from a meeting with @gyachdav and @vviro, but later, it was decided to begin with a simple table (the second widget). Currently, the colors and sizes of the circles do not have any meaning, and it lacks features (no expansion possible) since it is unclear if it really will be used. (See also #48)

@vviro What do you think about it? Should we build it as a real widget?

**Comment by vviro** [comment]
@chaoran-chen I would first focus on working with real data and on simple UI for that (so I'd leave the bubbles for later). Most important is the real data - having it one can extend the simple UI meaningfully. For example, one could add filters for the timeline view (if there are too many entries and if we have a good way to filter the events) - but we need to see first whether this is relevant and feasible, all depending on the data.

**Comment by ansjin** [comment]
@chaoran-chen Looks quite good! :) 
Yeah I can provide with you the timeline data of the music pieces also. I only need the separate raw text file of the music piece along with the music piece of which the file is!

**Comment by vviro** [comment]
Are you also going to get timed data also from the unstructured data and relations groups? If so, can they already provide any samples, or when this will be possible?

**Comment by chaoran-chen** [comment]
It has been already requested:
https://github.com/MusicConnectionMachine/api/issues/22

**Comment by goldbergtatyana** [comment]
I like the Timeline widget very much. Since it is possible to zoom in/out into the widget a large number of events can be displayed. It would be great if the events could be supported by links to their sources. Not all sources are equally reliable and if there is info coming from a less reliable source, then the frame surrounding the text of the event could be displayed in a lighter color. Again, I think its a great widget!

**Comment by goldbergtatyana** [comment]
As to the third widget: I love the idea, too! The visualization is original, colorful and informative. If the information within the circles would remain condensed to 1-3 words and if we would define only a few classes (1) born, died, 2) married to and kids, 3) studied at, 4) travelled to, 5) famous pieces written, 6) professional appointmens, 7) friends with) and color the circles accordingly to these few classes only, it would allow a visualization that is super easy to grasp and would also make comparison of biographies of musicians very easy (this concept btw could be extended to comparisons of anything). It would be great seeing the third bubbles widget being introduced to the world as well!

I agree with @vviro that the Timeline widget has a priority now.

**Comment by kordianbruck** [comment]
@chaoran-chen can you please work through this issue an create sub issues and then close this one? Its not maintainable with this wall of text. Thanks

**Comment by chaoran-chen** [comment]
We forgot to close it but I think that there are no sub-issues that have to be created.
