### ISSUE TITLE
Setup Elasticsearch

### ISSUE THREAD

**Issue by chaoran-chen** [MusicConnectionMachine/VisualizationG5#6]
The result of this task could be a simple document with instructions to setup Elasticsearch and import our mock data, so that all the others can replicate it easily.

**Comment by sacdallago** [comment]
(strong) Suggestion: set up a docker container to build elastic search (/the tool) with your dependencies and such and then set up automatic deployment of the docker container via docker hub.

More:
1. https://www.sdxcentral.com/cloud/containers/definitions/what-is-docker-container-open-source-project/
1. https://docs.docker.com/docker-hub/builds/

**Comment by chaoran-chen** [comment]
Thanks @sacdallago for the great advice! I will start doing it right now.
