### ISSUE TITLE
Demo for Timeline with real data

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/VisualizationG5#63]
Do you have a demo somewhere with the real data (sample) that we can look at?

**Comment by chaoran-chen** [comment]
Do you mean this (which I have already posted several times)?
http://54.68.164.199:8080/timeline-app.html

**Comment by kordianbruck** [comment]
Yes exactly - we couldn't find it. When can we see it with real data from the API?

**Comment by chaoran-chen** [comment]
When https://github.com/MusicConnectionMachine/api/issues/22 is done.

**Comment by chaoran-chen** [comment]
A demo is there and the connection with the API is covered by #64 -> closed.
