### ISSUE TITLE
Embedding of widgets in other pages

### ISSUE THREAD

**Issue by pfent** [MusicConnectionMachine/VisualizationG5#65]
Is there a way to embed the widgets into another site? Example code for this would probably to be handy.  
Also, is there an API to 'tell' your widgets, what to display? E.g.:
* set query
* automatically scroll to data
* etc.

**Comment by joern-vh** [comment]
Have a look at the [Documentation Site](http://54.68.164.199:8083/). I think this is where a Demo is hosted. @chaoran-chen may you deploy the new Version? :)

**Comment by pfent** [comment]
Neat! @gyachdav @vviro I think this is exactly what we were looking for?

I'd expect a link to this in the README… Maybe you can add this and be sure, that you'll get all the kudos from my side 💃

**Comment by sacdallago** [comment]
Also, if this thing is hosted on MS instead of using the ip can you use the autogenerated DNS entry? It _feels_ a bit prettier :)

**Comment by gyachdav** [comment]
This is very nice! @pfent  please open an issue on G6 to add a link to this documentations from the About column in the SPA footer. thanks
