### ISSUE TITLE
Integrate with group 6 and deploy to same machine

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/VisualizationG5#78]
I think it would be smart to serve the SPA and the Widgets from the same machine. This is actually quite simple.

As we have now included this repo as a submodule in the other project, we can run the build for the widgets in the Dockerfile of group 6 and then copy the files to the according subfolders. ( /widgets/map/ - etc.)

This saves you the hassle of deploying your own machine and save us money.

**Comment by chaoran-chen** [comment]
I will do it after #73 is merged.
